language: python
python:
  - "2.6"
  - "2.7"
env: CFLAGS="-O0"

cache:
  directories:
    - $HOME/.cache/pip

script:
  python setup.py test
after_success:
  - coveralls

# See: http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false