language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env: CFLAGS="-O0"

#cache:
#  directories:
#    - $HOME/.cache/pip

before_install:

script:
  python setup.py test
after_success:
  - coveralls

# See: http://docs.travis-ci.com/user/migrating-from-legacy/
sudo: false